function Trig_Initialization_DefenceActions takes nothing returns nothing
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Tower_Protect, EVENT_PLAYER_UNIT_SELL)
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Spirit_Income, EVENT_PLAYER_UNIT_SELL)
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Basic_Strategy, EVENT_PLAYER_UNIT_SELL)
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Advanced_Strategy, EVENT_PLAYER_UNIT_SELL)
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Spirit_Item, EVENT_PLAYER_UNIT_SELL)
    call TriggerRegisterUnitEvent(gg_trg_Hidden_Summon, udg_BaseB[0], EVENT_UNIT_SELL)
    call TriggerRegisterUnitEvent(gg_trg_Hidden_Summon, udg_BaseA[0], EVENT_UNIT_SELL)
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Defence_BL, EVENT_PLAYER_UNIT_SELL)
    call AddUnitToStockBJ('n03X', gg_unit_h00D_0013, 1, 1)
    call AddUnitToStockBJ('n03X', gg_unit_h01Q_0033, 1, 1)
    call AddUnitToStockBJ('n03X', gg_unit_h01Q_0048, 1, 1)
    call AddUnitToStockBJ('n03X', gg_unit_h01Q_0059, 1, 1)
    call AddUnitToStockBJ('n03X', gg_unit_h01Q_0118, 1, 1)
    call AddUnitToStockBJ('n03X', gg_unit_h01Q_0119, 1, 1)
    if udg_GameMode / 100 != 3 then
        call TriggerRegisterAnyUnitEventBJ(gg_trg_Defence_Eating, EVENT_PLAYER_UNIT_SELL)
        call TriggerRegisterUnitEvent(gg_trg_Defence_Control_1, udg_BaseA[1], EVENT_UNIT_SELL)
        call AddUnitToStockBJ('n02W', udg_BaseA[1], 1, 1)
        call AddUnitToStockBJ('n02I', udg_BaseA[1], 1, 1)
        call AddUnitToStockBJ('n02X', udg_BaseA[1], 1, 1)
        call TriggerRegisterUnitEvent(gg_trg_Defence_Control_1, udg_BaseA[2], EVENT_UNIT_SELL)
        call AddUnitToStockBJ('n02W', udg_BaseA[2], 1, 1)
        call AddUnitToStockBJ('n02I', udg_BaseA[2], 1, 1)
        call AddUnitToStockBJ('n02X', udg_BaseA[2], 1, 1)
        call TriggerRegisterAnyUnitEventBJ(gg_trg_Defence_DefArea, EVENT_PLAYER_UNIT_SELL)
        call AddUnitToStockBJ('n02J', udg_BaseA[1], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[2], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[6], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[7], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[8], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[9], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[10], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[11], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[12], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[13], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[14], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseA[15], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[1], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[2], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[6], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[7], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[8], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[9], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[10], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[11], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[12], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[13], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[14], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseA[15], 1, 1)
    endif
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Defence_God, EVENT_PLAYER_UNIT_SELL)
    call AddUnitToStockBJ('n02M', gg_unit_h00U_0019, 1, 1)
    call AddUnitToStockBJ('n02M', gg_unit_h01Q_0120, 1, 1)
    call AddUnitToStockBJ('n02M', gg_unit_h01Q_0121, 1, 1)
    call AddUnitToStockBJ('n02M', gg_unit_h01Q_0122, 1, 1)
    call AddUnitToStockBJ('n02M', gg_unit_h01Q_0123, 1, 1)
    call AddUnitToStockBJ('n02M', gg_unit_h01Q_0124, 1, 1)
    if udg_GameMode / 100 != 3 then
        call TriggerRegisterAnyUnitEventBJ(gg_trg_Defence_SCV, EVENT_PLAYER_UNIT_SELL)
        call TriggerRegisterUnitEvent(gg_trg_Defence_Control_2, udg_BaseB[1], EVENT_UNIT_SELL)
        call TriggerRegisterUnitEvent(gg_trg_Defence_Control_2, udg_BaseB[2], EVENT_UNIT_SELL)
        call AddUnitToStockBJ('n03W', udg_BaseB[1], 1, 1)
        call AddUnitToStockBJ('n03U', udg_BaseB[1], 1, 1)
        call AddUnitToStockBJ('n03V', udg_BaseB[1], 1, 1)
        call AddUnitToStockBJ('n03W', udg_BaseB[2], 1, 1)
        call AddUnitToStockBJ('n03U', udg_BaseB[2], 1, 1)
        call AddUnitToStockBJ('n03V', udg_BaseB[2], 1, 1)
        call TriggerRegisterAnyUnitEventBJ(gg_trg_Defence_SpdArea, EVENT_PLAYER_UNIT_SELL)
        call AddUnitToStockBJ('n02J', udg_BaseB[1], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[2], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[6], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[7], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[8], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[9], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[10], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[11], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[12], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[13], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[14], 1, 1)
        call AddUnitToStockBJ('n02J', udg_BaseB[15], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[1], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[2], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[6], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[7], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[8], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[9], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[10], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[11], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[12], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[13], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[14], 1, 1)
        call AddUnitToStockBJ('n02K', udg_BaseB[15], 1, 1)
    endif
endfunction

function InitTrig_Initialization_Defence takes nothing returns nothing
    set gg_trg_Initialization_Defence = CreateTrigger()
    call TriggerAddAction(gg_trg_Initialization_Defence, function Trig_Initialization_DefenceActions)
endfunction