function Trig_Init_Yuyuko_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('U006')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    call SetHeroLifeIncreaseValue(h, 27)
    call SetHeroManaIncreaseValue(h, 8)
    call SetHeroManaBaseRegenValue(h, 0.2)
    set udg_SK_uuzre_switch = 0
    set udg_SK_uuz03_switch = 0
    call UnitAddAbility(h, 'A0MM')
    set gg_trg_Yuyuko_Rekill = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuyuko_Rekill, h, EVENT_UNIT_DAMAGED)
    call TriggerRegisterUnitStateEvent(gg_trg_Yuyuko_Rekill, h, UNIT_STATE_LIFE, LESS_THAN, 5.0)
    call TriggerAddCondition(gg_trg_Yuyuko_Rekill, Condition(function Trig_Yuyuko_Rekill_Conditions))
    call TriggerAddAction(gg_trg_Yuyuko_Rekill, function Trig_Yuyuko_Rekill_Actions)
    set gg_trg_Yuyuko01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuyuko01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Yuyuko01, Condition(function Trig_Yuyuko01_Conditions))
    call TriggerAddAction(gg_trg_Yuyuko01, function Trig_Yuyuko01_Actions)
    set gg_trg_Yuyuko01_Damage = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Yuyuko01_Damage)
    call TriggerAddCondition(gg_trg_Yuyuko01_Damage, Condition(function Trig_Yuyuko01_Damage_Conditions))
    call TriggerAddAction(gg_trg_Yuyuko01_Damage, function Trig_Yuyuko01_Damage_Actions)
    set gg_trg_Yuyuko02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuyuko02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Yuyuko02, Condition(function Trig_Yuyuko02_Conditions))
    call TriggerAddAction(gg_trg_Yuyuko02, function Trig_Yuyuko02_Actions)
    set gg_trg_Yuyuko03 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuyuko03, h, EVENT_UNIT_HERO_SKILL)
    call TriggerAddCondition(gg_trg_Yuyuko03, Condition(function Trig_Yuyuko03_ID))
    call TriggerAddAction(gg_trg_Yuyuko03, function Trig_Yuyuko03_Learn)
    set gg_trg_Yuyuko03_Damage = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuyuko03_Damage, h, EVENT_UNIT_HERO_SKILL)
    call TriggerAddCondition(gg_trg_Yuyuko03_Damage, Condition(function Trig_Yuyuko03_Damage_Conditions))
    call TriggerAddAction(gg_trg_Yuyuko03_Damage, function Trig_Yuyuko03_Damage_Learn)
    set gg_trg_Yuyuko03_Switch = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuyuko03_Switch, h, EVENT_UNIT_ISSUED_ORDER)
    call TriggerAddAction(gg_trg_Yuyuko03_Switch, function Trig_Yuyuko03_Switch_Actions)
    set gg_trg_Yuyuko04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuyuko04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Yuyuko04, Condition(function Trig_Yuyuko04_Conditions1))
    call TriggerAddAction(gg_trg_Yuyuko04, function Trig_Yuyuko04_Actions1)
    call FirstAbilityInit('A05B')
    call FirstAbilityInit('A05G')
    call FirstAbilityInit('A05H')
    call FirstAbilityInit('A05I')
    call FirstAbilityInit('A05J')
    call FirstAbilityInit('A05F')
    call FirstAbilityInit('A0MS')
    call FirstAbilityInit('A0MR')
    call FirstAbilityInit('A0MQ')
    set h = null
endfunction

function InitTrig_Init_Yuyuko takes nothing returns nothing
    set gg_trg_Init_Yuyuko = CreateTrigger()
    call TriggerAddAction(gg_trg_Init_Yuyuko, function Trig_Init_Yuyuko_Actions)
endfunction