function Trig_CenterModeData_Initialization_Actions takes nothing returns nothing
    local integer i = 0
    local integer j = 0
    set udg_GameSetting_Gold_A = 40
    set udg_GameSetting_Gold_B = 40
    set udg_MapRegion = gg_rct_Center_Camera_Area
    set udg_PlayerReviveHouse[0] = gg_unit_H01Q_0128
    set udg_PlayerReviveHouse[1] = gg_unit_H01Q_0127
    set udg_PlayerReviveHouse[2] = gg_unit_H01Q_0129
    set udg_PlayerReviveHouse[3] = gg_unit_H01Q_0130
    set udg_PlayerReviveHouse[4] = gg_unit_H01Q_0126
    set udg_PlayerReviveHouse[6] = gg_unit_H01Q_0104
    set udg_PlayerReviveHouse[7] = gg_unit_H01Q_0110
    set udg_PlayerReviveHouse[8] = gg_unit_H01Q_0090
    set udg_PlayerReviveHouse[9] = gg_unit_H01Q_0125
    set udg_PlayerReviveHouse[10] = gg_unit_H01Q_0109
    set udg_RevivePoint[0] = GetRectCenter(gg_rct_ReviveCA)
    set udg_RevivePoint[1] = GetRectCenter(gg_rct_ReviveCB)
    set udg_RecoverPoint[0] = GetRectCenter(gg_rct_ReviveCA)
    set udg_RecoverPoint[1] = GetRectCenter(gg_rct_ReviveCB)
    set udg_BirthPoint[0] = GetRectCenter(gg_rct_ReviveCA)
    set udg_BirthPoint[1] = GetRectCenter(gg_rct_ReviveCB)
    set udg_CommonPoint = GetRectCenter(gg_rct_CommonAreaC)
    set udg_SpawnLocA[0] = GetRectCenter(gg_rct_ReviveCA)
    set udg_SpawnLocA[1] = GetRectCenter(gg_rct_ReviveCA)
    set udg_SpawnLocA[2] = GetRectCenter(gg_rct_ReviveCA)
    set udg_SpawnLocA[3] = GetRectCenter(gg_rct_ReviveCA)
    set udg_SpawnLocB[0] = GetRectCenter(gg_rct_ReviveCB)
    set udg_SpawnLocB[1] = GetRectCenter(gg_rct_ReviveCB)
    set udg_SpawnLocB[2] = GetRectCenter(gg_rct_ReviveCB)
    set udg_SpawnLocB[3] = GetRectCenter(gg_rct_ReviveCB)
    set j = 1
    set i = 0
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_BaseAC)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_5)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_4)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_3)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_2)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_1)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_0)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_BaseBC)
    set j = 0
    set i = 0
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_BaseAC)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_5)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_4)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_3)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_2)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_1)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_0)
    set i = i + 1
    set udg_SpawnRouteA[j * 16 + i] = GetRectCenter(gg_rct_BaseBC)
    set j = 0
    set i = 0
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_BaseBC)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_0)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_1)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_2)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_3)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_4)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_0_5)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_BaseAC)
    set j = 1
    set i = 0
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_BaseBC)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_0)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_1)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_2)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_3)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_4)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_WayPoint_C_1_5)
    set i = i + 1
    set udg_SpawnRouteB[j * 16 + i] = GetRectCenter(gg_rct_BaseAC)
    set udg_SpawnLocA[0] = GetRectCenter(gg_rct_ReviveCA)
    set udg_SpawnLocA[1] = GetRectCenter(gg_rct_ReviveCA)
    set udg_SpawnLocA[2] = GetRectCenter(gg_rct_ReviveCA)
    set udg_SpawnLocA[3] = GetRectCenter(gg_rct_ReviveCA)
    set udg_SpawnLocB[0] = GetRectCenter(gg_rct_ReviveCB)
    set udg_SpawnLocB[1] = GetRectCenter(gg_rct_ReviveCB)
    set udg_SpawnLocB[2] = GetRectCenter(gg_rct_ReviveCB)
    set udg_SpawnLocB[3] = GetRectCenter(gg_rct_ReviveCB)
    set udg_BaseA[0] = gg_unit_hvlt_0087
    set udg_BaseA[1] = gg_unit_hatw_0085
    set udg_BaseA[2] = gg_unit_hatw_0086
    call UnitAddAbility(udg_BaseA[1], 'A0NK')
    call UnitAddAbility(udg_BaseA[2], 'A0NK')
    set udg_BaseA[3] = null
    set udg_BaseA[4] = null
    set udg_BaseA[5] = null
    set udg_BaseA[6] = gg_unit_hatw_0084
    set udg_BaseA[7] = null
    set udg_BaseA[8] = gg_unit_hatw_0049
    set udg_BaseA[9] = null
    set udg_BaseA[10] = null
    set udg_BaseA[11] = null
    set udg_BaseA[12] = null
    set udg_BaseA[13] = null
    set udg_BaseA[14] = null
    set udg_BaseB[0] = gg_unit_hvlt_0088
    set udg_BaseB[1] = gg_unit_hatw_0077
    set udg_BaseB[2] = gg_unit_hatw_0075
    call UnitAddAbility(udg_BaseB[1], 'A0NK')
    call UnitAddAbility(udg_BaseB[2], 'A0NK')
    set udg_BaseB[3] = null
    set udg_BaseB[4] = null
    set udg_BaseB[5] = null
    set udg_BaseB[6] = gg_unit_hatw_0074
    set udg_BaseB[7] = null
    set udg_BaseB[8] = gg_unit_hatw_0078
    set udg_BaseB[9] = null
    set udg_BaseB[10] = null
    set udg_BaseB[11] = null
    set udg_BaseB[12] = null
    set udg_BaseB[13] = null
    set udg_BaseB[14] = null
    call SetUnitInvulnerable(udg_BaseA[0], true)
    call SetUnitInvulnerable(udg_BaseB[0], true)
    call TriggerRegisterPlayerUnitEventSimple(gg_trg_Tower_Break_A, udg_PlayerA[0], EVENT_PLAYER_UNIT_DEATH)
    call TriggerRegisterPlayerUnitEventSimple(gg_trg_Tower_Break_B, udg_PlayerB[0], EVENT_PLAYER_UNIT_DEATH)
    call TriggerExecute(gg_trg_SpawnAbility)
    set i = 0
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseA)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_00)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_01)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_02)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_03)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_04)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_05)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseB)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseA)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B0)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B1)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B2)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B3)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B4)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B5)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseB)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseA)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C0)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C1)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C2)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C3)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C4)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C5)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseB)
    set i = 32
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseB)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_05)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_04)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_03)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_02)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_01)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_00)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseA)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseB)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B5)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B4)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B3)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B2)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B1)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_B0)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseA)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseB)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C5)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C4)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C3)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C2)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C1)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_AI_Waypoint_C0)
    set i = i + 1
    set udg_AI_Waypoints[i] = GetRectCenter(gg_rct_BaseA)
endfunction

function InitTrig_CenterModeData_Initialization takes nothing returns nothing
    set gg_trg_CenterModeData_Initialization = CreateTrigger()
    call TriggerAddAction(gg_trg_CenterModeData_Initialization, function Trig_CenterModeData_Initialization_Actions)
endfunction