function Trig_Init_Abilities_HideButtons takes nothing returns nothing
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A01T', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A06Q', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A09O', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A055', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A07I', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0A7', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0BB', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0CZ', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0DM', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0EO', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0E7', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0FA', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0HH', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0IM', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0JB', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0L9', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A096', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0ML', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0S1', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0S7', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0SB', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0SC', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0SD', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0SI', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0SK', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0TB', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0TC', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0TD', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0TX', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0UF', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0V6', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0VB', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0VE', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0WO', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0WX', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0WY', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0WZ', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0WP', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0X0', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0X1', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0X2', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0YP', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0Z1', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0Z5', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A122', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A128', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A129', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A12A', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A124', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A12M', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A19W', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A00O', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0B9', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1Z4', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1Z5', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1Z6', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1Z7', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A0Z8', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1BF', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1CG', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1CW', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1CX', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1CY', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1CZ', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1E7', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1HH', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1HI', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1HJ', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1HK', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1I3', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1I4', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1I5', false)
    call SetPlayerAbilityAvailable(GetEnumPlayer(), 'A1FE', false)
endfunction

function Trig_Init_Abilities_Actions takes nothing returns nothing
    set udg_AbilityInitDummy = CreateUnit(Player(15), 'h00D', 19450.0, -2100.0, 0)
    call ForForce(bj_FORCE_ALL_PLAYERS, function Trig_Init_Abilities_HideButtons)
    call FirstAbilityInit('A0UM')
    call FirstAbilityInit('A0RV')
    call FirstAbilityInit('A0U8')
    call FirstAbilityInit('A145')
    call FirstAbilityInit('A195')
    call FirstAbilityInit('A01L')
    call FirstAbilityInit('A0ZI')
    call FirstAbilityInit('A0ZG')
    call FirstAbilityInit('A0ZH')
    call FirstAbilityInit('A18P')
endfunction

function InitTrig_Init_Abilities takes nothing returns nothing
    set gg_trg_Init_Abilities = CreateTrigger()
    call TriggerAddAction(gg_trg_Init_Abilities, function Trig_Init_Abilities_Actions)
endfunction