function Trig_Initial_Marisa_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('H000')
    local integer i = 0
    local timer t
    call FirstAbilityInit('A1C0')
    call FirstAbilityInit('A1C2')
    call FirstAbilityInit('A1C3')
    call FirstAbilityInit('A1C4')
    call FirstAbilityInit('A1G2')
    call FirstAbilityInit('A107')
    call FirstAbilityInit('A02L')
    call FirstAbilityInit('A02Q')
    call FirstAbilityInit('A02M')
    call FirstAbilityInit('A040')
    call FirstAbilityInit('A0V4')
    call FirstAbilityInit('A041')
    call FirstAbilityInit('A043')
    call FirstAbilityInit('A044')
    call FirstAbilityInit('A045')
    call FirstAbilityInit('A03Z')
    call FirstAbilityInit('A042')
    call FirstAbilityInit('A05T')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    set t = CreateTimer()
    call SaveUnitHandle(udg_ht, GetHandleId(t), 1, h)
    call SaveTimerHandle(udg_Hashtable_CDInReimu, GetHandleId(h), 'A02L' * 10 + 0, t)
    call UnitAddAbility(h, 'A02L')
    call UnitAddAbility(h, 'A02Q')
    call SetHeroLifeIncreaseValue(h, 26)
    call SetHeroManaIncreaseValue(h, 5)
    call SetHeroManaBaseRegenValue(h, 0.2)
    call RecHeroBasicArmorValue(h, 0.0)
    call RecHeroIncreArmorValue(h, 0.1)
    call RecHeroAttackBaseValue(h, 25)
    call RecHeroAttackUppeValue(h, 34)
    call RecHeroStaterTypeValue(h, 3)
    set i = 0
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 0, 'A107')
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 1, 1)
    call SaveReal(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 2, 500.0 * 1.0)
    call SaveReal(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 3, 0.0 * 1.0)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 4, 0)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 5, 215)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 6, 215)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 7, 15)
    call SqSaveUnitCircl(h, i, 0)
    set i = 1
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 0, 'A040')
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 1, 1)
    call SaveReal(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 2, 450.0 * 1.0)
    call SaveReal(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 3, 50.0 * 1.0)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 4, 0)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 5, 215)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 6, 215)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 7, 215)
    call SqSaveUnitCircl(h, i, 0)
    set i = 2
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 0, 'A041')
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 1, 0)
    set i = 3
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 0, 'A03Z')
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 1, 0)
    set i = 4
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 0, 'A042')
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 1, 1)
    call SaveReal(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 2, 900.0 * 1.0)
    call SaveReal(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 3, 0.0 * 1.0)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 4, 0)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 5, 115)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 6, 115)
    call SaveInteger(udg_Hashtable_CastSq_Id, GetHandleId(h), i * 10 + 7, 115)
    call SqSaveUnitCircl(h, i, 0)
    set gg_trg_MarisaEx = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_MarisaEx, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_MarisaEx, Condition(function Trig_MarisaEx_Conditions))
    call TriggerAddAction(gg_trg_MarisaEx, function Trig_MarisaEx_Actions)
    set gg_trg_Marisa01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Marisa01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Marisa01, Condition(function Trig_Marisa01_Conditions))
    call TriggerAddAction(gg_trg_Marisa01, function Trig_Marisa01_Actions)
    set gg_trg_Marisa02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Marisa02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Marisa02, Condition(function Trig_Stars_Conditions))
    call TriggerAddAction(gg_trg_Marisa02, function Trig_Stars_Actions)
    if gg_trg_Marisa02_Damage == null then
        set gg_trg_Marisa02_Damage = CreateTrigger()
        call RegisterAnyUnitDamage(gg_trg_Marisa02_Damage)
        call TriggerAddCondition(gg_trg_Marisa02_Damage, Condition(function Trig_Marisa02_Damage_Conditions))
        call TriggerAddAction(gg_trg_Marisa02_Damage, function Trig_Marisa02_Damage_Actions)
    endif
    set gg_trg_Marisa03 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Marisa03, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Marisa03, Condition(function Trig_Marisa03_Conditions))
    call TriggerAddAction(gg_trg_Marisa03, function Trig_Marisa03_Actions)
    set gg_trg_Marisa04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Marisa04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Marisa04, Condition(function Trig_Marisa04_Conditions))
    call TriggerAddAction(gg_trg_Marisa04, function Trig_Marisa04_Actions)
    set h = null
endfunction

function InitTrig_Initial_Marisa takes nothing returns nothing
    set gg_trg_Initial_Marisa = CreateTrigger()
    call TriggerAddAction(gg_trg_Initial_Marisa, function Trig_Initial_Marisa_Actions)
endfunction