function Trig_Init_Alice_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('H01A')
    local player w = GetOwningPlayer(h)
    local integer task = GetHandleId(h)
    call FirstAbilityInit('A10W')
    call FirstAbilityInit('A10X')
    call FirstAbilityInit('A10Y')
    call FirstAbilityInit('A10Z')
    call FirstAbilityInit('A0TO')
    call FirstAbilityInit('A0GZ')
    call FirstAbilityInit('A0HR')
    call FirstAbilityInit('AIsr')
    call FirstAbilityInit('A0HG')
    call FirstAbilityInit('A0HW')
    call FirstAbilityInit('A0HI')
    call FirstAbilityInit('A0HJ')
    call FirstAbilityInit('A0HN')
    call FirstAbilityInit('Aeth')
    call FirstAbilityInit('A0HO')
    call FirstAbilityInit('A0HP')
    call FirstAbilityInit('A0HQ')
    call FirstAbilityInit('A0HU')
    call FirstAbilityInit('A0HA')
    call FirstAbilityInit('A0HC')
    call FirstAbilityInit('A0HB')
    call FirstAbilityInit('Agho')
    call FirstAbilityInit('A0H0')
    call FirstAbilityInit('A0H1')
    call FirstAbilityInit('A0HD')
    call FirstAbilityInit('A0HL')
    call FirstAbilityInit('A0HT')
    call FirstAbilityInit('A0GV')
    call FirstAbilityInit('A0GY')
    call FirstAbilityInit('A0GW')
    call FirstAbilityInit('A0GX')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    if not udg_Repick then
        call DestroyTrigger(GetTriggeringTrigger())
    endif
    call SetHeroLifeIncreaseValue(h, 35)
    call SetHeroManaIncreaseValue(h, 9)
    call SetHeroManaBaseRegenValue(h, 0.6)
    call RecHeroBasicArmorValue(h, 0.0)
    call RecHeroIncreArmorValue(h, 0.0)
    call RecHeroAttackBaseValue(h, 26)
    call RecHeroAttackUppeValue(h, 35)
    call RecHeroStaterTypeValue(h, 3)
    call DisableTrigger(gg_trg_Alice_Dolls)
    call DestroyTrigger(gg_trg_Alice_Dolls)
    set gg_trg_Alice_Dolls = CreateTrigger()
    call DisableTrigger(gg_trg_Alice_Dolls_KIA)
    call DestroyTrigger(gg_trg_Alice_Dolls_KIA)
    set gg_trg_Alice_Dolls_KIA = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Alice_Dolls_KIA, w, EVENT_PLAYER_UNIT_DEATH, null)
    call TriggerAddCondition(gg_trg_Alice_Dolls_KIA, Condition(function Trig_Alice_Dolls_KIA_Conditions))
    call TriggerAddAction(gg_trg_Alice_Dolls_KIA, function Trig_Alice_Dolls_KIA_Actions)
    call DisableTrigger(gg_trg_Alice_Dolls_Back)
    call DestroyTrigger(gg_trg_Alice_Dolls_Back)
    set gg_trg_Alice_Dolls_Back = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Alice_Dolls_Back, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Alice_Dolls_Back, Condition(function Trig_Alice_Dolls_Back_Conditions))
    call TriggerAddAction(gg_trg_Alice_Dolls_Back, function Trig_Alice_Dolls_Back_Actions)
    call SaveInteger(udg_sht, task, 1, 2)
    call SaveInteger(udg_sht, task, 2, 2)
    call SaveInteger(udg_sht, task, 3, 2)
    call SaveGroupHandle(udg_sht, task, 1, CreateGroup())
    call SaveGroupHandle(udg_sht, task, 2, CreateGroup())
    call SaveGroupHandle(udg_sht, task, 3, CreateGroup())
    call DisableTrigger(gg_trg_Alice)
    call DestroyTrigger(gg_trg_Alice)
    set gg_trg_Alice = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Alice, h, EVENT_UNIT_HERO_SKILL)
    call TriggerAddAction(gg_trg_Alice, function Trig_Alice_Actions)
    call DisableTrigger(gg_trg_Alice01)
    call DestroyTrigger(gg_trg_Alice01)
    set gg_trg_Alice01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Alice01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Alice01, Condition(function Trig_Alice01_Conditions))
    call TriggerAddAction(gg_trg_Alice01, function Trig_Alice01_Actions)
    call DisableTrigger(gg_trg_Alice02)
    call DestroyTrigger(gg_trg_Alice02)
    set gg_trg_Alice02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Alice02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Alice02, Condition(function Trig_Alice02_Conditions))
    call TriggerAddAction(gg_trg_Alice02, function Trig_Alice02_Actions)
    call DisableTrigger(gg_trg_Alice03)
    call DestroyTrigger(gg_trg_Alice03)
    set gg_trg_Alice03 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Alice03, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Alice03, Condition(function Trig_Alice03_Conditions))
    call TriggerAddAction(gg_trg_Alice03, function Trig_Alice03_Actions)
    call DisableTrigger(gg_trg_Alice_Onboard)
    call DestroyTrigger(gg_trg_Alice_Onboard)
    set gg_trg_Alice_Onboard = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Alice_Onboard, h, EVENT_UNIT_LOADED)
    call TriggerAddCondition(gg_trg_Alice_Onboard, Condition(function Trig_Alice_Onboard_Conditions))
    call TriggerAddAction(gg_trg_Alice_Onboard, function Trig_Alice_Onboard_Actions)
    call DisableTrigger(gg_trg_Shanghai01)
    call DestroyTrigger(gg_trg_Shanghai01)
    set gg_trg_Shanghai01 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Shanghai01, w, EVENT_PLAYER_UNIT_ISSUED_ORDER, null)
    call TriggerAddCondition(gg_trg_Shanghai01, Condition(function Trig_Shanghai01_Conditions))
    call DisableTrigger(gg_trg_Shanghai02)
    call DestroyTrigger(gg_trg_Shanghai02)
    set gg_trg_Shanghai02 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Shanghai02, w, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_Shanghai02, Condition(function Trig_Shanghai02_Conditions))
    call TriggerAddAction(gg_trg_Shanghai02, function Trig_Shanghai02_Actions)
    call DisableTrigger(gg_trg_Shanghai03)
    call DestroyTrigger(gg_trg_Shanghai03)
    set gg_trg_Shanghai03 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Shanghai03, w, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_Shanghai03, Condition(function Trig_Shanghai03_Conditions))
    call TriggerAddAction(gg_trg_Shanghai03, function Trig_Shanghai03_Actions)
    call DisableTrigger(gg_trg_Shanghai04)
    call DestroyTrigger(gg_trg_Shanghai04)
    set gg_trg_Shanghai04 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Shanghai04, w, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_Shanghai04, Condition(function Trig_Shanghai04_Conditions))
    call TriggerAddAction(gg_trg_Shanghai04, function Trig_Shanghai04_Actions)
    call DisableTrigger(gg_trg_Shanghai04_Issue)
    call DestroyTrigger(gg_trg_Shanghai04_Issue)
    set gg_trg_Shanghai04_Issue = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Shanghai04_Issue, w, EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER, null)
    call TriggerAddCondition(gg_trg_Shanghai04_Issue, Condition(function Trig_Shanghai04_Issue_Conditions))
    call TriggerAddAction(gg_trg_Shanghai04_Issue, function Trig_Shanghai04_Issue_Actions)
    call DisableTrigger(gg_trg_Shanghai04_Alice)
    call DestroyTrigger(gg_trg_Shanghai04_Alice)
    set gg_trg_Shanghai04_Alice = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Shanghai04_Alice, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Shanghai04_Alice, Condition(function Trig_Shanghai04_Alice_Conditions))
    call TriggerAddAction(gg_trg_Shanghai04_Alice, function Trig_Shanghai04_Alice_Actions)
    call DisableTrigger(gg_trg_Hourai01)
    call DestroyTrigger(gg_trg_Hourai01)
    set gg_trg_Hourai01 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Hourai01, w, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_Hourai01, Condition(function Trig_Hourai01_Conditions))
    call TriggerAddAction(gg_trg_Hourai01, function Trig_Hourai01_Actions)
    call DisableTrigger(gg_trg_Hourai02)
    call DestroyTrigger(gg_trg_Hourai02)
    set gg_trg_Hourai02 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Hourai02, w, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerRegisterPlayerUnitEvent(gg_trg_Hourai02, w, EVENT_PLAYER_UNIT_SPELL_ENDCAST, null)
    call TriggerAddCondition(gg_trg_Hourai02, Condition(function Trig_Hourai02_Conditions))
    call TriggerAddAction(gg_trg_Hourai02, function Trig_Hourai02_Actions)
    call DisableTrigger(gg_trg_Hourai04)
    call DestroyTrigger(gg_trg_Hourai04)
    set gg_trg_Hourai04 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Hourai04, w, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_Hourai04, Condition(function Trig_Hourai04_Conditions))
    call TriggerAddAction(gg_trg_Hourai04, function Trig_Hourai04_Actions)
    call DisableTrigger(gg_trg_Hourai04_Damage)
    call DestroyTrigger(gg_trg_Hourai04_Damage)
    set gg_trg_Hourai04_Damage = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Hourai04_Damage)
    call TriggerAddCondition(gg_trg_Hourai04_Damage, Condition(function Trig_Hourai04_Damage_Conditions))
    call TriggerAddAction(gg_trg_Hourai04_Damage, function Trig_Hourai04_Damage_Actions)
    call DisableTrigger(gg_trg_NewEngland01)
    call DestroyTrigger(gg_trg_NewEngland01)
    set gg_trg_NewEngland01 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_NewEngland01, w, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_NewEngland01, Condition(function Trig_NewEngland01_Conditions))
    call TriggerAddAction(gg_trg_NewEngland01, function Trig_NewEngland01_Actions)
    call DisableTrigger(gg_trg_NewEngland04)
    call DestroyTrigger(gg_trg_NewEngland04)
    set gg_trg_NewEngland04 = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_NewEngland04, w, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_NewEngland04, Condition(function Trig_NewEngland04_Conditions))
    call TriggerAddAction(gg_trg_NewEngland04, function Trig_NewEngland04_Actions)
    set h = CreateUnitAtLoc(Player(15), 'o000', udg_BackStage, 0.0)
    call UnitAddAbility(h, 'A0GV')
    call UnitAddAbility(h, 'A0GW')
    call UnitAddAbility(h, 'A0GX')
    call UnitAddAbility(h, 'A0GY')
    call UnitAddAbility(h, 'A0GZ')
    call UnitAddAbility(h, 'A0H0')
    call UnitAddAbility(h, 'A0H1')
    call UnitAddAbility(h, 'A0H2')
    call UnitAddAbility(h, 'A0H3')
    call UnitAddAbility(h, 'A0H4')
    call UnitAddAbility(h, 'A0H5')
    call UnitInitAddAttack(h)
    call UnitAddAbility(h, 'A0HA')
    call UnitAddAbility(h, 'A0HB')
    call UnitAddAbility(h, 'A0HC')
    call UnitAddAbility(h, 'A0HD')
    call UnitAddAbility(h, 'A0HE')
    call UnitAddAbility(h, 'A0HF')
    call UnitAddAbility(h, 'A0HG')
    call UnitAddAbility(h, 'A0HH')
    call UnitAddAbility(h, 'A0HI')
    call UnitAddAbility(h, 'A0HJ')
    call UnitAddAbility(h, 'A0HK')
    call UnitAddAbility(h, 'A0HL')
    call UnitAddAbility(h, 'A0HM')
    call UnitAddAbility(h, 'A0HN')
    call UnitAddAbility(h, 'A0HO')
    call UnitAddAbility(h, 'A0HP')
    call UnitAddAbility(h, 'A0HQ')
    call UnitAddAbility(h, 'A0HR')
    call UnitAddAbility(h, 'A0HS')
    call UnitAddAbility(h, 'A0HT')
    call UnitAddAbility(h, 'A0HU')
    call UnitAddAbility(h, 'A0HW')
    call UnitAddAbility(h, 'A0HX')
    set w = null
    set h = null
endfunction

function InitTrig_Init_Alice takes nothing returns nothing
    set gg_trg_Init_Alice = CreateTrigger()
    call TriggerAddAction(gg_trg_Init_Alice, function Trig_Init_Alice_Actions)
endfunction