function Trig_Initialing_Lily_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('E023')
    call FirstAbilityInit('A0GV')
    call FirstAbilityInit('A0GW')
    call FirstAbilityInit('A0GX')
    call FirstAbilityInit('A0GY')
    call FirstAbilityInit('A0GZ')
    call FirstAbilityInit('A0H0')
    call FirstAbilityInit('A0H1')
    call FirstAbilityInit('A0H2')
    call FirstAbilityInit('A0H3')
    call FirstAbilityInit('A0H4')
    call FirstAbilityInit('A0H5')
    call FirstAbilityInit('A0HA')
    call FirstAbilityInit('A0HB')
    call FirstAbilityInit('A0HC')
    call FirstAbilityInit('A0HD')
    call FirstAbilityInit('A0HE')
    call FirstAbilityInit('A0HF')
    call FirstAbilityInit('A0HG')
    call FirstAbilityInit('A0HI')
    call FirstAbilityInit('A0HJ')
    call FirstAbilityInit('A0HK')
    call FirstAbilityInit('A0HL')
    call FirstAbilityInit('A0HM')
    call FirstAbilityInit('A0HN')
    call FirstAbilityInit('A0HO')
    call FirstAbilityInit('A0HP')
    call FirstAbilityInit('A0HQ')
    call FirstAbilityInit('A0HR')
    call FirstAbilityInit('A0HS')
    call FirstAbilityInit('A0HT')
    call FirstAbilityInit('A0HU')
    call FirstAbilityInit('A0HW')
    call FirstAbilityInit('A0HX')
    call FirstAbilityInit('A0WQ')
    call FirstAbilityInit('A0WK')
    call FirstAbilityInit('A1A6')
    call FirstAbilityInit('A0WL')
    call FirstAbilityInit('A0X3')
    call FirstAbilityInit('A0IL')
    call FirstAbilityInit('A0X4')
    call FirstAbilityInit('A0VT')
    call FirstAbilityInit('A0X5')
    call FirstAbilityInit('A0X6')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    call SetHeroLifeIncreaseValue(h, 25)
    call SetHeroManaIncreaseValue(h, 10)
    call SetHeroManaBaseRegenValue(h, 0.5)
    call RecHeroBasicArmorValue(h, 0.0)
    call RecHeroIncreArmorValue(h, 0.0)
    call RecHeroAttackBaseValue(h, 26)
    call RecHeroAttackUppeValue(h, 35)
    call RecHeroStaterTypeValue(h, 3)
    set gg_trg_LilyEx = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_LilyEx, h, EVENT_UNIT_HERO_REVIVABLE)
    call TriggerRegisterUnitEvent(gg_trg_LilyEx, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_LilyEx, Condition(function Trig_LilyEx_Conditions))
    set gg_trg_Lily01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Lily01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Lily01, Condition(function Trig_Lily01_Conditions))
    call TriggerAddAction(gg_trg_Lily01, function Trig_Lily01_Actions)
    set gg_trg_Lily02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Lily02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Lily02, Condition(function Trig_Lily02_Conditions))
    call TriggerAddAction(gg_trg_Lily02, function Trig_Lily02_Actions)
    set gg_trg_Lily03 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Lily03, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Lily03, Condition(function Trig_Lily03_Conditions))
    call TriggerAddAction(gg_trg_Lily03, function Trig_Lily03_Actions)
    set gg_trg_Lily04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Lily04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Lily04, Condition(function Trig_Lily04_Conditions))
    call TriggerAddAction(gg_trg_Lily04, function Trig_Lily04_Actions)
    set h = null
endfunction

function InitTrig_Initialing_Lily takes nothing returns nothing
    set gg_trg_Initialing_Lily = CreateTrigger()
    call TriggerAddAction(gg_trg_Initialing_Lily, function Trig_Initialing_Lily_Actions)
endfunction