function Trig_Init_Merlin_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('E01W')
    local integer id = GetConvertedPlayerId(GetOwningPlayer(h))
    call FirstAbilityInit('A0O3')
    call FirstAbilityInit('A0RS')
    call FirstAbilityInit('A0S2')
    call FirstAbilityInit('A0S4')
    call FirstAbilityInit('A0SE')
    call FirstAbilityInit('A0RX')
    call FirstAbilityInit('A0RY')
    call FirstAbilityInit('A084')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    if not udg_Repick then
        call DestroyTrigger(GetTriggeringTrigger())
    endif
    call SetHeroLifeIncreaseValue(h, 38)
    call SetHeroManaIncreaseValue(h, 4)
    call SetHeroManaBaseRegenValue(h, 0.4)
    set udg_SK_Merlin = h
    set udg_SK_MerlinEx_Count = 1
    call DisableTrigger(gg_trg_MerlinAttack)
    call DestroyTrigger(gg_trg_MerlinAttack)
    set gg_trg_MerlinAttack = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_MerlinAttack)
    call TriggerAddCondition(gg_trg_MerlinAttack, Condition(function Trig_MerlinAttack_Conditions))
    call TriggerAddAction(gg_trg_MerlinAttack, function Trig_MerlinAttack_Actions)
    call DisableTrigger(gg_trg_MerlinEx)
    call DestroyTrigger(gg_trg_MerlinEx)
    set gg_trg_MerlinEx = CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_MerlinEx, EVENT_PLAYER_UNIT_DEATH)
    call TriggerAddCondition(gg_trg_MerlinEx, Condition(function Trig_MerlinEx_Conditions))
    call TriggerAddAction(gg_trg_MerlinEx, function Trig_MerlinEx_Actions)
    call DisableTrigger(gg_trg_Merlin01)
    call DestroyTrigger(gg_trg_Merlin01)
    set gg_trg_Merlin01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Merlin01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Merlin01, Condition(function Trig_Merlin01_Conditions))
    call TriggerAddAction(gg_trg_Merlin01, function Trig_Merlin01_Actions)
    call DisableTrigger(gg_trg_Merlin01_DeSurice)
    call DestroyTrigger(gg_trg_Merlin01_DeSurice)
    set gg_trg_Merlin01_DeSurice = CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Merlin01_DeSurice, EVENT_PLAYER_UNIT_ISSUED_ORDER)
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Merlin01_DeSurice, EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Merlin01_DeSurice, EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER)
    call TriggerAddCondition(gg_trg_Merlin01_DeSurice, Condition(function Trig_Merlin01_DeSurice_Conditions))
    call TriggerAddAction(gg_trg_Merlin01_DeSurice, function Trig_Merlin01_DeSurice_Actions)
    call DisableTrigger(gg_trg_Merlin02)
    call DestroyTrigger(gg_trg_Merlin02)
    set gg_trg_Merlin02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Merlin02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Merlin02, Condition(function Trig_Merlin02_Conditions))
    call TriggerAddAction(gg_trg_Merlin02, function Trig_Merlin02_Actions)
    call DisableTrigger(gg_trg_Merlin03)
    call DestroyTrigger(gg_trg_Merlin03)
    set gg_trg_Merlin03 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Merlin03, h, EVENT_UNIT_HERO_SKILL)
    call TriggerAddCondition(gg_trg_Merlin03, Condition(function Trig_Merlin03_Conditions))
    call TriggerAddAction(gg_trg_Merlin03, function Trig_Merlin03_Actions)
    call DisableTrigger(gg_trg_Merlin04)
    call DestroyTrigger(gg_trg_Merlin04)
    set gg_trg_Merlin04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Merlin04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Merlin04, Condition(function Trig_Merlin04_Conditions))
    call TriggerAddAction(gg_trg_Merlin04, function Trig_Merlin04_Actions)
    call DisableTrigger(gg_trg_Merlin04_Damage)
    call DestroyTrigger(gg_trg_Merlin04_Damage)
    set gg_trg_Merlin04_Damage = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Merlin04_Damage, h, EVENT_UNIT_DAMAGED)
    call TriggerAddCondition(gg_trg_Merlin04_Damage, Condition(function Trig_Merlin04_Damage_Conditions))
    call TriggerAddAction(gg_trg_Merlin04_Damage, function Trig_Merlin04_Damage_Actions)
    set h = null
endfunction

function InitTrig_Init_Merlin takes nothing returns nothing
    set gg_trg_Init_Merlin = CreateTrigger()
    call TriggerAddAction(gg_trg_Init_Merlin, function Trig_Init_Merlin_Actions)
endfunction