function Trig_Initial_Yuugi_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('H00K')
    call FirstAbilityInit('A03Q')
    call FirstAbilityInit('A0RM')
    call FirstAbilityInit('A11C')
    call FirstAbilityInit('A08B')
    call FirstAbilityInit('Aloc')
    call FirstAbilityInit('A118')
    call FirstAbilityInit('A08C')
    call FirstAbilityInit('A08D')
    call FirstAbilityInit('A17W')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    if not udg_Repick then
        call DestroyTrigger(GetTriggeringTrigger())
    endif
    call SetHeroLifeIncreaseValue(h, 35)
    call SetHeroManaIncreaseValue(h, 8)
    call SetHeroManaBaseRegenValue(h, 0.6)
    set udg_SK_Yuugi = h
    call UnitInitAddAttack(h)
    call DisableTrigger(gg_trg_Yuugi_Roar)
    call DestroyTrigger(gg_trg_Yuugi_Roar)
    set gg_trg_Yuugi_Roar = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuugi_Roar, h, EVENT_UNIT_DAMAGED)
    call TriggerAddCondition(gg_trg_Yuugi_Roar, Condition(function Trig_Yuugi_Roar_Conditions))
    call TriggerAddAction(gg_trg_Yuugi_Roar, function Trig_Yuugi_Roar_Actions)
    call DisableTrigger(gg_trg_Yuugi01)
    call DestroyTrigger(gg_trg_Yuugi01)
    set gg_trg_Yuugi01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuugi01, h, EVENT_UNIT_HERO_SKILL)
    call TriggerAddCondition(gg_trg_Yuugi01, Condition(function Trig_Yuugi01_Conditions))
    call DisableTrigger(gg_trg_Yuugi01Cast)
    call DestroyTrigger(gg_trg_Yuugi01Cast)
    set gg_trg_Yuugi01Cast = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuugi01Cast, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Yuugi01Cast, Condition(function Trig_Yuugi01Cast_Conditions))
    call TriggerAddAction(gg_trg_Yuugi01Cast, function Trig_Yuugi01Cast_Actions)
    call DisableTrigger(gg_trg_Yuugi02)
    call DestroyTrigger(gg_trg_Yuugi02)
    set gg_trg_Yuugi02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuugi02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Yuugi02, Condition(function Trig_Yuugi02_Conditions))
    call TriggerAddAction(gg_trg_Yuugi02, function Trig_Yuugi02_Actions)
    call AddingLBuff(0, 'A118', 'B06H')
    call DisableTrigger(gg_trg_Yuugi03New)
    call DestroyTrigger(gg_trg_Yuugi03New)
    set gg_trg_Yuugi03New = CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Yuugi03New, EVENT_PLAYER_UNIT_ATTACKED)
    call TriggerAddCondition(gg_trg_Yuugi03New, Condition(function Trig_Yuugi03New_Conditions))
    call TriggerAddAction(gg_trg_Yuugi03New, function Trig_Yuugi03New_Actions)
    call DisableTrigger(gg_trg_Yuugi04)
    call DestroyTrigger(gg_trg_Yuugi04)
    set gg_trg_Yuugi04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Yuugi04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Yuugi04, Condition(function Trig_Yuugi04_Conditions))
    call TriggerAddAction(gg_trg_Yuugi04, function Trig_Yuugi04_Actions)
    set h = null
endfunction

function InitTrig_Initial_Yuugi takes nothing returns nothing
    set gg_trg_Initial_Yuugi = CreateTrigger()
    call TriggerAddAction(gg_trg_Initial_Yuugi, function Trig_Initial_Yuugi_Actions)
endfunction