function Trig_Initial_Cirno_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('E009')
    call FirstAbilityInit('A11O')
    call FirstAbilityInit('A11P')
    call FirstAbilityInit('A11Q')
    call FirstAbilityInit('A11R')
    call FirstAbilityInit('A0TE')
    call FirstAbilityInit('A0MZ')
    call FirstAbilityInit('A0MY')
    call FirstAbilityInit('A0MX')
    call FirstAbilityInit('A03W')
    call FirstAbilityInit('A06F')
    call FirstAbilityInit('A03X')
    call FirstAbilityInit('A04J')
    call FirstAbilityInit('A057')
    call FirstAbilityInit('A056')
    call FirstAbilityInit('A058')
    call FirstAbilityInit('A0MW')
    call FirstAbilityInit('A0C6')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    if not udg_Repick then
        call DestroyTrigger(GetTriggeringTrigger())
    endif
    call SetHeroLifeIncreaseValue(h, 31)
    call SetHeroManaIncreaseValue(h, 18)
    call SetHeroManaBaseRegenValue(h, 0.6)
    set udg_SK_Cirno_Cirno = h
    call DisableTrigger(gg_trg_CirnoBaga)
    call DestroyTrigger(gg_trg_CirnoBaga)
    set gg_trg_CirnoBaga = CreateTrigger()
    call TriggerRegisterTimerEvent(gg_trg_CirnoBaga, 0.1, true)
    call TriggerAddCondition(gg_trg_CirnoBaga, Condition(function Trig_CirnoBaga_Conditions))
    call DisableTrigger(gg_trg_Cirno01)
    call DestroyTrigger(gg_trg_Cirno01)
    set gg_trg_Cirno01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Cirno01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Cirno01, Condition(function Trig_Cirno01_Conditions))
    call TriggerAddAction(gg_trg_Cirno01, function Trig_Cirno01_Actions)
    call DisableTrigger(gg_trg_Cirno02)
    call DestroyTrigger(gg_trg_Cirno02)
    set gg_trg_Cirno02 = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Cirno02)
    call TriggerAddCondition(gg_trg_Cirno02, Condition(function Trig_Cirno02_Conditions))
    call TriggerAddAction(gg_trg_Cirno02, function Trig_Cirno02_Actions)
    call DisableTrigger(gg_trg_Cirno02Cast)
    call DestroyTrigger(gg_trg_Cirno02Cast)
    set gg_trg_Cirno02Cast = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Cirno02Cast, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Cirno02Cast, Condition(function Trig_Cirno02Cast_Conditions))
    call TriggerAddAction(gg_trg_Cirno02Cast, function Trig_Cirno02Cast_Actions)
    call AddingLBuff(0, 'A04J', 0)
    call AddingLBuff(0, 'A057', 'B05A')
    call DisableTrigger(gg_trg_Cirno03)
    call DestroyTrigger(gg_trg_Cirno03)
    set gg_trg_Cirno03 = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Cirno03)
    call TriggerAddCondition(gg_trg_Cirno03, Condition(function Trig_Cirno03_Conditions))
    call TriggerAddAction(gg_trg_Cirno03, function Trig_Cirno03_Actions)
    call DisableTrigger(gg_trg_Cirno03Cast)
    call DestroyTrigger(gg_trg_Cirno03Cast)
    set gg_trg_Cirno03Cast = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Cirno03Cast, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Cirno03Cast, Condition(function Trig_Cirno03Cast_Conditions))
    call TriggerAddAction(gg_trg_Cirno03Cast, function Trig_Cirno03Cast_Actions)
    call DisableTrigger(gg_trg_Cirno04)
    call DestroyTrigger(gg_trg_Cirno04)
    set gg_trg_Cirno04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Cirno04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Cirno04, Condition(function Trig_Cirno04_Conditions))
    call TriggerAddAction(gg_trg_Cirno04, function Trig_Cirno04_Actions)
    set h = null
endfunction

function InitTrig_Initial_Cirno takes nothing returns nothing
    set gg_trg_Initial_Cirno = CreateTrigger()
    call TriggerAddAction(gg_trg_Initial_Cirno, function Trig_Initial_Cirno_Actions)
endfunction