function Trig_Initial_Nitori_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('H00M')
    local timer t = CreateTimer()
    call FirstAbilityInit('A094')
    call FirstAbilityInit('A0V4')
    call FirstAbilityInit('A0GF')
    call FirstAbilityInit('A0LL')
    call FirstAbilityInit('A0GH')
    call FirstAbilityInit('A17F')
    call FirstAbilityInit('A0LK')
    call FirstAbilityInit('A0GG')
    call FirstAbilityInit('A097')
    call FirstAbilityInit('A0IL')
    call FirstAbilityInit('A0OE')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    if not udg_Repick then
        call DestroyTrigger(GetTriggeringTrigger())
    endif
    call UnitInitAddAttack(h)
    call SetHeroLifeIncreaseValue(h, 26)
    call SetHeroManaIncreaseValue(h, 7)
    call SetHeroManaBaseRegenValue(h, 0.7)
    call DisableTrigger(gg_trg_NitoriDS)
    call DestroyTrigger(gg_trg_NitoriDS)
    set gg_trg_NitoriDS = CreateTrigger()
    call TriggerRegisterPlayerEvent(gg_trg_NitoriDS, GetOwningPlayer(h), EVENT_PLAYER_END_CINEMATIC)
    call TriggerAddCondition(gg_trg_NitoriDS, Condition(function NitoriDS))
    call DisableTrigger(gg_trg_Nitori01)
    call DestroyTrigger(gg_trg_Nitori01)
    set gg_trg_Nitori01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Nitori01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Nitori01, Condition(function Trig_Nitori01_Conditions))
    call TriggerAddAction(gg_trg_Nitori01, function Trig_Nitori01_Actions)
    set udg_Nitori_RealInt = GetHeroInt(h, true)
    call SaveUnitHandle(udg_sht, GetHandleId(t), 0, h)
    call TimerStart(t, 0.5, true, function NitoriEx)
    call DisableTrigger(gg_trg_Nitori02)
    call DestroyTrigger(gg_trg_Nitori02)
    set gg_trg_Nitori02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Nitori02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Nitori02, Condition(function Trig_Nitori02_Conditions))
    call TriggerAddAction(gg_trg_Nitori02, function Trig_Nitori02_Actions)
    call DisableTrigger(gg_trg_Nitori03)
    call DestroyTrigger(gg_trg_Nitori03)
    set gg_trg_Nitori03 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Nitori03, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Nitori03, Condition(function Trig_Nitori03_Conditions))
    call TriggerAddAction(gg_trg_Nitori03, function Trig_Nitori03_Actions)
    call DisableTrigger(gg_trg_Nitori03_Active)
    call DestroyTrigger(gg_trg_Nitori03_Active)
    set gg_trg_Nitori03_Active = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Nitori03_Active)
    call TriggerAddCondition(gg_trg_Nitori03_Active, Condition(function Trig_Nitori03_Active_Conditions))
    call TriggerAddAction(gg_trg_Nitori03_Active, function Trig_Nitori03_Active_Actions)
    call DisableTrigger(gg_trg_Nitori03_Cast)
    call DestroyTrigger(gg_trg_Nitori03_Cast)
    set gg_trg_Nitori03_Cast = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Nitori03_Cast, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Nitori03_Cast, Condition(function Trig_Nitori03_Cast_Conditions))
    call TriggerAddAction(gg_trg_Nitori03_Cast, function Trig_Nitori03_Cast_Actions)
    call DisableTrigger(gg_trg_Nitori04)
    call DestroyTrigger(gg_trg_Nitori04)
    set gg_trg_Nitori04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Nitori04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Nitori04, Condition(function Trig_Nitori04_Conditions))
    call TriggerAddAction(gg_trg_Nitori04, function Trig_Nitori_Skill4_Actions)
    call DisableTrigger(gg_trg_Nitori04_Damage)
    call DestroyTrigger(gg_trg_Nitori04_Damage)
    set gg_trg_Nitori04_Damage = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Nitori04_Damage)
    call TriggerAddCondition(gg_trg_Nitori04_Damage, Condition(function Trig_Nitori04_Damage_Conditions))
    call TriggerAddAction(gg_trg_Nitori04_Damage, function Trig_Nitori04_Damage_Actions)
    call UnitAddAbility(h, 'A096')
    call UnitRemoveAbility(h, 'A096')
    set h = null
endfunction

function InitTrig_Initial_Nitori takes nothing returns nothing
    set gg_trg_Initial_Nitori = CreateTrigger()
    call TriggerAddAction(gg_trg_Initial_Nitori, function Trig_Initial_Nitori_Actions)
endfunction