function Trig_Initial_Captain_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('E00Q')
    local player p
    local timer t = CreateTimer()
    call FirstAbilityInit('A0AB')
    call FirstAbilityInit('A0IL')
    call FirstAbilityInit('A0AA')
    call FirstAbilityInit('Aloc')
    call FirstAbilityInit('Avul')
    call FirstAbilityInit('A0A6')
    call FirstAbilityInit('A0A8')
    call FirstAbilityInit('A0A9')
    call FirstAbilityInit('A1A3')
    call FirstAbilityInit('A1AX')
    call FirstAbilityInit('A0AG')
    call FirstAbilityInit('A1AW')
    call FirstAbilityInit('A0AF')
    call FirstAbilityInit('A0AI')
    call FirstAbilityInit('A0RP')
    call FirstAbilityInit('A0AH')
    call FirstAbilityInit('A10O')
    call FirstAbilityInit('A10I')
    call FirstAbilityInit('A10J')
    if h == null then
        return
    endif
    set udg_SK_Caption04_Hero = h
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    if not udg_Repick then
        call DestroyTrigger(GetTriggeringTrigger())
    endif
    set p = GetOwningPlayer(h)
    call SetHeroLifeIncreaseValue(h, 26)
    call SetHeroManaIncreaseValue(h, 11)
    call SetHeroManaBaseRegenValue(h, 0.2)
    call UnitAddAbility(h, 'A10O')
    call DisableTrigger(gg_trg_Captain04_Select)
    call DestroyTrigger(gg_trg_Captain04_Select)
    set gg_trg_Captain04_Select = CreateTrigger()
    call TimerStart(t, 15.0, false, function Trig_Captain04_Select_Actions)
    call DisableTrigger(gg_trg_Captain01)
    call DestroyTrigger(gg_trg_Captain01)
    set gg_trg_Captain01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Captain01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Captain01, Condition(function Trig_Captain01_Conditions))
    call TriggerAddAction(gg_trg_Captain01, function Trig_Captain01_Actions)
    call DisableTrigger(gg_trg_Captain02)
    call DestroyTrigger(gg_trg_Captain02)
    set gg_trg_Captain02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Captain02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Captain02, Condition(function Trig_Captain02_Conditions))
    call TriggerAddAction(gg_trg_Captain02, function Trig_Captain02_Actions)
    call DisableTrigger(gg_trg_Captain03)
    call DestroyTrigger(gg_trg_Captain03)
    set gg_trg_Captain03 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Captain03, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Captain03, Condition(function Trig_bocai_Conditions))
    call TriggerAddAction(gg_trg_Captain03, function Trig_bocai_Actions)
    call DisableTrigger(gg_trg_Captain04_Learn)
    call DestroyTrigger(gg_trg_Captain04_Learn)
    set gg_trg_Captain04_Learn = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Captain04_Learn, h, EVENT_UNIT_HERO_SKILL)
    call TriggerAddCondition(gg_trg_Captain04_Learn, Condition(function Trig_Captain04_Learn_Conditions))
    call TriggerAddAction(gg_trg_Captain04_Learn, function Trig_Captain04_Learn_Actions)
    call DisableTrigger(gg_trg_Captain04_Reg)
    call DestroyTrigger(gg_trg_Captain04_Reg)
    set gg_trg_Captain04_Reg = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Captain04_Reg, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Captain04_Reg, Condition(function Trig_Captain04_Reg_Conditions))
    call TriggerAddAction(gg_trg_Captain04_Reg, function Trig_Captain04_Reg_Actions)
    call DisableTrigger(gg_trg_Captain04_LostShip)
    call DestroyTrigger(gg_trg_Captain04_LostShip)
    set gg_trg_Captain04_LostShip = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Captain04_LostShip, p, EVENT_PLAYER_UNIT_DEATH, null)
    call TriggerAddCondition(gg_trg_Captain04_LostShip, Condition(function Trig_Captain04_LostShip_Conditions))
    call TriggerAddAction(gg_trg_Captain04_LostShip, function Trig_Captain04_LostShip_Actions)
    call DisableTrigger(gg_trg_Captain04_jiasu)
    call DestroyTrigger(gg_trg_Captain04_jiasu)
    set gg_trg_Captain04_jiasu = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Captain04_jiasu, p, EVENT_PLAYER_UNIT_LOADED, null)
    call TriggerAddCondition(gg_trg_Captain04_jiasu, Condition(function Trig_Captain04_jiasu_Conditions))
    call TriggerAddAction(gg_trg_Captain04_jiasu, function Trig_Captain04_jiasu_Actions)
    call DisableTrigger(gg_trg_Captain04_yongjiutingbo)
    call DestroyTrigger(gg_trg_Captain04_yongjiutingbo)
    set gg_trg_Captain04_yongjiutingbo = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Captain04_yongjiutingbo, p, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_Captain04_yongjiutingbo, Condition(function Trig_yongjiutingbo_Conditions))
    call TriggerAddAction(gg_trg_Captain04_yongjiutingbo, function Trig_yongjiutingbo_Actions)
    call DisableTrigger(gg_trg_Captain04_nihility)
    call DestroyTrigger(gg_trg_Captain04_nihility)
    set gg_trg_Captain04_nihility = CreateTrigger()
    call TriggerRegisterPlayerUnitEvent(gg_trg_Captain04_nihility, p, EVENT_PLAYER_UNIT_SPELL_EFFECT, null)
    call TriggerAddCondition(gg_trg_Captain04_nihility, Condition(function Trig_Captain04_nihility_Conditions))
    call TriggerAddAction(gg_trg_Captain04_nihility, function Trig_Captain04_nihility_Actions)
    call DisableTrigger(gg_trg_Captain04_CallBack)
    call DestroyTrigger(gg_trg_Captain04_CallBack)
    set gg_trg_Captain04_CallBack = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Captain04_CallBack)
    call TriggerRegisterPlayerUnitEvent(gg_trg_Captain04_CallBack, p, EVENT_PLAYER_UNIT_SPELL_FINISH, null)
    call TriggerAddCondition(gg_trg_Captain04_CallBack, Condition(function Trig_Captain04_CallBack_Conditions))
    set h = null
endfunction

function InitTrig_Initial_Captain takes nothing returns nothing
    set gg_trg_Initial_Captain = CreateTrigger()
    call TriggerAddAction(gg_trg_Initial_Captain, function Trig_Initial_Captain_Actions)
endfunction