function Trig_Initial_Toramaru_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('H01N')
    call FirstAbilityInit('A10O')
    call FirstAbilityInit('A0P4')
    call FirstAbilityInit('A0QX')
    call FirstAbilityInit('A0QY')
    call FirstAbilityInit('A0QZ')
    call FirstAbilityInit('A0R0')
    call FirstAbilityInit('A0R1')
    call FirstAbilityInit('A0R2')
    call FirstAbilityInit('A0P2')
    call FirstAbilityInit('A0SS')
    call FirstAbilityInit('A0ST')
    call FirstAbilityInit('A0R3')
    call FirstAbilityInit('A1GC')
    call FirstAbilityInit('A0Z4')
    call FirstAbilityInit('A0P3')
    call FirstAbilityInit('A0SR')
    call FirstAbilityInit('A0V4')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    if not udg_Repick then
        call DestroyTrigger(GetTriggeringTrigger())
    endif
    call SetHeroLifeIncreaseValue(h, 34)
    call SetHeroManaIncreaseValue(h, 8)
    call SetHeroManaBaseRegenValue(h, 0.5)
    set udg_SK_Toramaru = h
    call UnitAddAbility(h, 'A0P4')
    call DisableTrigger(gg_trg_ToramaruDB)
    call DestroyTrigger(gg_trg_ToramaruDB)
    set gg_trg_ToramaruDB = CreateTrigger()
    call TriggerRegisterTimerEvent(gg_trg_ToramaruDB, 18.0, true)
    call TriggerAddAction(gg_trg_ToramaruDB, function Trig_ToramaruDB_Actions)
    call DisableTrigger(gg_trg_Toramaru01_Attack)
    call DestroyTrigger(gg_trg_Toramaru01_Attack)
    set gg_trg_Toramaru01_Attack = CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Toramaru01_Attack, EVENT_PLAYER_UNIT_ATTACKED)
    call TriggerAddCondition(gg_trg_Toramaru01_Attack, Condition(function Trig_Toramaru01_Attack_Conditions))
    call TriggerAddAction(gg_trg_Toramaru01_Attack, function Trig_Toramaru01_Attack_Actions)
    call DisableTrigger(gg_trg_Toramaru01)
    call DestroyTrigger(gg_trg_Toramaru01)
    set gg_trg_Toramaru01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Toramaru01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Toramaru01, Condition(function Trig_Toramaru01_Conditions))
    call TriggerAddAction(gg_trg_Toramaru01, function Trig_Toramaru01_Actions)
    call DisableTrigger(gg_trg_Toramaru02)
    call DestroyTrigger(gg_trg_Toramaru02)
    set gg_trg_Toramaru02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Toramaru02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Toramaru02, Condition(function Trig_Toramaru02_Conditions))
    call TriggerAddAction(gg_trg_Toramaru02, function Trig_Toramaru02_Actions)
    call DisableTrigger(gg_trg_Toramaru02_Learn)
    call DestroyTrigger(gg_trg_Toramaru02_Learn)
    set gg_trg_Toramaru02_Learn = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Toramaru02_Learn, h, EVENT_UNIT_HERO_SKILL)
    call TriggerAddCondition(gg_trg_Toramaru02_Learn, Condition(function Trig_Toramaru02_Learn_Conditions))
    call TriggerAddAction(gg_trg_Toramaru02_Learn, function Trig_Toramaru02_Learn_Actions)
    call DisableTrigger(gg_trg_Toramaru03)
    call DestroyTrigger(gg_trg_Toramaru03)
    set gg_trg_Toramaru03 = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Toramaru03)
    call TriggerAddCondition(gg_trg_Toramaru03, Condition(function Trig_Toramaru03_Conditions))
    call TriggerAddAction(gg_trg_Toramaru03, function Trig_Toramaru03_Actions)
    call DisableTrigger(gg_trg_Toramaru03_Kill)
    call DestroyTrigger(gg_trg_Toramaru03_Kill)
    set gg_trg_Toramaru03_Kill = CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_Toramaru03_Kill, EVENT_PLAYER_UNIT_DEATH)
    call TriggerAddCondition(gg_trg_Toramaru03_Kill, Condition(function Trig_Toramaru03_Kill_Conditions))
    call TriggerAddAction(gg_trg_Toramaru03_Kill, function Trig_Toramaru03_Kill_Actions)
    call DisableTrigger(gg_trg_Toramaru04)
    call DestroyTrigger(gg_trg_Toramaru04)
    set gg_trg_Toramaru04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Toramaru04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Toramaru04, Condition(function Trig_Toramaru04_Conditions))
    call TriggerAddAction(gg_trg_Toramaru04, function Trig_Toramaru04_Actions)
    set h = null
endfunction

function InitTrig_Initial_Toramaru takes nothing returns nothing
    set gg_trg_Initial_Toramaru = CreateTrigger()
    call TriggerAddAction(gg_trg_Initial_Toramaru, function Trig_Initial_Toramaru_Actions)
endfunction