function Trig_Initial_Satsuki_Actions takes nothing returns nothing
    local unit h = GetCharacterHandle('O01B')
    if h == null then
        return
    endif
    call DebugMsg(GetHeroProperName(h) + " skill initialization completed")
    call SetHeroLifeIncreaseValue(h, 29)
    call SetHeroManaIncreaseValue(h, 1)
    call SetHeroManaBaseRegenValue(h, 0.4)
    set gg_trg_SatsukiEx = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_SatsukiEx, h, EVENT_UNIT_HERO_LEVEL)
    call TriggerAddAction(gg_trg_SatsukiEx, function Trig_SatsukiEx_Actions)
    call DisableTrigger(gg_trg_Satsuki01)
    call DestroyTrigger(gg_trg_Satsuki01)
    set gg_trg_Satsuki01 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Satsuki01, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Satsuki01, Condition(function Trig_Satsuki01_Conditions))
    call TriggerAddAction(gg_trg_Satsuki01, function Trig_Satsuki01_Actions)
    call DisableTrigger(gg_trg_Satsuki02)
    call DestroyTrigger(gg_trg_Satsuki02)
    set gg_trg_Satsuki02 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Satsuki02, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Satsuki02, Condition(function Trig_Satsuki02_Conditions))
    call TriggerAddAction(gg_trg_Satsuki02, function Trig_Satsuki02_Actions)
    call DisableTrigger(gg_trg_Satsuki03)
    call DestroyTrigger(gg_trg_Satsuki03)
    set gg_trg_Satsuki03 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Satsuki03, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Satsuki03, Condition(function Trig_Satsuki03_Conditions))
    call TriggerAddAction(gg_trg_Satsuki03, function Trig_Satsuki03_Actions)
    call DisableTrigger(gg_trg_Satsuki04)
    call DestroyTrigger(gg_trg_Satsuki04)
    set gg_trg_Satsuki04 = CreateTrigger()
    call TriggerRegisterUnitEvent(gg_trg_Satsuki04, h, EVENT_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_Satsuki04, Condition(function Trig_Satsuki04_Conditions))
    call TriggerAddAction(gg_trg_Satsuki04, function Trig_Satsuki04_Actions)
    call DisableTrigger(gg_trg_Satsuki_Attack)
    call DestroyTrigger(gg_trg_Satsuki_Attack)
    set gg_trg_Satsuki_Attack = CreateTrigger()
    call RegisterAnyUnitDamage(gg_trg_Satsuki_Attack)
    call TriggerAddCondition(gg_trg_Satsuki_Attack, Condition(function Trig_Satsuki_Attack_Conditions))
    call TriggerAddAction(gg_trg_Satsuki_Attack, function Trig_Satsuki_Attack_Actions)
    call UnitAddAbility(h, 'A1HG')
    call FirstAbilityInit('A17W')
endfunction

function InitTrig_Initial_Satsuki takes nothing returns nothing
    set gg_trg_Initial_Satsuki = CreateTrigger()
    call TriggerAddAction(gg_trg_Initial_Satsuki, function Trig_Initial_Satsuki_Actions)
endfunction